language: julia
os:
  - linux
  - osx

julia:
  - 1.5
  - nightly

script: travis_wait julia --project -e 'using Pkg; Pkg.test(; coverage=true)'
matrix:
  - fast_finish: true
  - allow_failures:
    - julia: nightly

codecov: true
coveralls: true

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
