name = "UMAP"
uuid = "c4f8c510-2410-5be4-91d7-4fbaeb39457e"
authors = ["Dillon Daudert <dillongdaudert@gmail.com>"]
version = "0.1.5"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
NearestNeighborDescent = "dd2c4c9e-a32f-5b2f-b342-08c2f244fce8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Arpack = "0.4"
Distances = "0.8"
LsqFit = "0.6, 0.7, 0.8, 0.9, 0.10"
NearestNeighborDescent = "0.3"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
