[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
NearestNeighborDescent = "dd2c4c9e-a32f-5b2f-b342-08c2f244fce8"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoStaticHTML = "359b1769-a58e-495b-9770-312e911026ad"
UMAP = "c4f8c510-2410-5be4-91d7-4fbaeb39457e"
